apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp
  namespace: task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapp
  template:
    metadata:
      labels:
        app: taskapp
    spec:
      serviceAccountName: taskapp-sa
      containers:
      - name: taskapp
        image: mytaskapp:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/tasksdb"
        - name: MONGO_DB
          value: "tasksdb"
---
apiVersion: v1
kind: Service
metadata:
  name: taskapp-svc
  namespace: task-app
spec:
  selector:
    app: taskapp
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
