apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: task-app
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: /data/mongo-data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: task-app
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
