apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskapp-sa
  namespace: task-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: taskapp-role
  namespace: task-app
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: taskapp-rb
  namespace: task-app
subjects:
- kind: ServiceAccount
  name: taskapp-sa
  namespace: task-app
roleRef:
  kind: Role
  name: taskapp-role
  apiGroup: rbac.authorization.k8s.io
